import {pageRoot,crumb,fetchJSON,showLoadError,refreshShared,safeText,maybeAutoSupportPrompt} from './app.js';
import {postRows} from './render.js';
import {flag,visit,finalChoice,environmentSnapshot,atmosphereStage,currentReturnSubmitted,hasFlag} from './state.js';
(async()=>{try{
 let data=await fetchJSON('data/posts.json');flag('viewedSquare');visit('square_archive');if(!finalChoice())data=data.filter(x=>!x.date.startsWith('2027-'));const p=new URLSearchParams(location.search);const y=p.get('year')||'2026',month=p.get('month')||'08',sort=p.get('sort')||'time',q=(p.get('q')||'').trim(),env=environmentSnapshot(),atmo=atmosphereStage();
 let items=data.filter(x=>x.date.startsWith(`${y}-${month}`));if(q)items=items.filter(x=>(x.title+x.author+x.category+x.summary+(x.realname||'')).includes(q));
 if(sort==='hot')items=[...items].sort((a,b)=>(b.replies||0)-(a.replies||0)||b.date.localeCompare(a.date));else if(sort==='archive')items=[...items].sort((a,b)=>a.date.localeCompare(b.date));else items=[...items].sort((a,b)=>b.date.localeCompare(a.date));
 const tab=(id,label)=>`<a class="${sort===id?'active':''}" href="square.html?year=${encodeURIComponent(y)}&month=${encodeURIComponent(month)}&sort=${id}${q?`&q=${encodeURIComponent(q)}`:''}">${label}</a>`;
 const after=finalChoice()?'<div class="notice-box small"><strong>归档同步提示：</strong>当前校园账户已不在公开在籍名单中。部分历史浏览记录可能仅保留在本机缓存。</div>':'';
 const quiet=atmo>=5?`<span>最新公开动态 ${atmo>=7?'1 小时前':atmo>=6?'43 分钟前':'21 分钟前'}</span>`:'<span>公开话题持续更新</span>';
 const archiveRec=currentReturnSubmitted()&&y==='2026'&&!hasFlag('viewedCatPost')?`<a class="forum-archive-rec" href="square-post.html?id=post_0829_a"><img src="assets/img/cat-1.jpg" alt="旧校园广场猫图缩略图"><span><small>历史公开归档推荐 · 2022-08-29</small><b>我的暑假正在一点一点没有.jpg</b><em>晚点回 · 高三闲聊</em></span></a>`:'';
 pageRoot().innerHTML=`${crumb([{label:'校园广场'}])}<section class="forum-shell"><div class="forum-head"><b>栖岚校园广场 · 公开归档</b><span class="tiny">归档月份 ${safeText(y)} / ${safeText(month)}</span></div><div class="forum-statusbar"><span>当前校园在线 <b>${env.online}</b></span><span>${safeText(env.weather)}</span>${y==='2026'?quiet:'<span>历史公开归档</span>'}</div><div style="padding:12px;background:#fff;border-bottom:1px solid #ccc"><form class="searchbar" method="get"><select class="form-control" name="year" style="max-width:150px">${(finalChoice()?['2027','2026','2022','2019','2017']:['2026','2022','2019','2017']).map(v=>`<option value="${v}" ${y===v?'selected':''}>${v}</option>`).join('')}</select><select class="form-control" name="month" style="max-width:130px"><option value="08" ${month==='08'?'selected':''}>8 月</option><option value="09" ${month==='09'?'selected':''}>9 月</option></select><input type="hidden" name="sort" value="${safeText(sort)}"><input class="form-control" name="q" value="${safeText(q)}" placeholder="搜索公开话题、作者或关键词"><button class="btn" type="submit">搜索</button></form></div><div class="forum-tabs">${tab('time','按时间')}${tab('hot','热门')}${tab('archive','公开归档')}</div>${archiveRec}<div class="forum-post-list">${postRows(items)}</div></section><div class="notice-box small">校园广场归档仅包含当年公开帖子与公开回复，不包含私信、已正常清理的删除内容或私人联系方式。</div>${after}`;
 refreshShared();maybeAutoSupportPrompt();
}catch(e){showLoadError(e)}})();
