import {pageRoot,crumb,refreshShared,serviceMeta} from './app.js';
import {reviewReady,flag,attentionSnapshot,finalChoice,setFinalChoice,currentReturnSubmitted} from './state.js';
import {maybeReviewButtonFlicker} from './anomaly.js';
import {playCue} from './audio.js';

const ending=finalChoice();
function endingHTML(kind){
  const map={
    stop:{title:'当前校园会话已结束',trace:'未发现可恢复的公开主题。',body:'系统已按“结束当前查询”关闭本次材料入口。次日学籍同步显示“校际转出 / 家庭长期迁居”，当前返校账户不再提供在籍服务。'},
    public:{title:'公开反馈已进入内容清理',trace:'公开主题缓存缩略图：1。',body:'你提交的公开反馈已从校园广场主索引移除。缓存中仍残留 1 个主题缩略图；次日学籍同步显示“校际转出 / 家庭长期迁居”。'},
    archive:{title:'历史附件已进入归档队列',trace:'2027 预同步：未处理历史附件 1。',body:'完整材料被写入校史附件队列。当前返校账户随后从在籍服务中移除；附件本身未被删除，但在下一学年预同步前始终保持“未处理”。'}
  },e=map[kind];
  return `${crumb([{label:'学生事务补充核验'}])}<section class="panel result-sheet"><div class="result-head"><div><div class="tiny muted">学生事务服务 · 事项回执</div><h2>${e.title}</h2></div><span class="badge gray">会话失效</span></div>${serviceMeta([['处理时间','08-30 18:42'],['当前账户','不可用'],['学籍同步','次日生效']])}<p>${e.body}</p><div class="result-grid"><div class="result-stat"><span>接驳班次</span><b>18:40</b></div><div class="result-stat"><span>车辆</span><b>校车 03</b></div><div class="result-stat"><span>服务流转</span><b>已交接</b></div></div><div class="business-note effective-info"><strong>目的服务机构：</strong>青岚青少年成长实践中心。当前回执未显示离场记录、后续联系方式或撤销事项。</div><div class="future-record effective-info"><span>下一学年索引预同步</span><b>${e.trace}</b></div><div class="divider"></div><div class="forum-epilogue"><div class="tiny muted">校园广场 · 2026-08-31 08:12</div><p><b>有人认识那个最近一直翻旧资料的人吗？</b></p><p class="small">回复：哪个？我们班没这个人吧。</p><p class="small">发帖人：可我昨天明明还……</p><div class="deleted-line">该主题不存在或已被清理。</div></div><div class="actions"><a class="btn primary" href="index.html">返回学校首页</a><a class="btn" href="search.html">打开站内搜索</a></div></section>`;
}

if(ending){
  pageRoot().innerHTML=endingHTML(ending);refreshShared();
}else if(!currentReturnSubmitted()||!reviewReady()){
  pageRoot().innerHTML=`${crumb([{label:'学生事务补充核验'}])}<section class="panel"><h2 class="section-title">学生事务补充核验</h2>${serviceMeta([['当前账户','****0417'],['待办事项','0'],['状态','暂无事项']])}<div class="notice-box">当前账户暂无可办理的补充核验事项。若由其他页面进入，请返回原业务页面继续核对。</div><div class="actions"><a class="btn primary" href="index.html">返回返校总览</a><a class="btn" href="my-return.html">我的返校</a></div></section>`;refreshShared();
}else{
  flag('openedReview');const a=attentionSnapshot();
  pageRoot().innerHTML=`${crumb([{label:'学生事务补充核验'}])}<div class="page-grid"><div><section class="panel"><h2 class="section-title">学生事务补充核验 <small>已进入人工服务流转</small></h2>${serviceMeta([['事项编号','QL-SR-2026-0830'],['集合时间','08-30 18:40'],['集合地点','综合服务楼西门']])}<div class="notice-box effective-info"><strong>事项来源：</strong>历史公开资料连续访问、人员状态交叉查询与旧索引兼容性复核。当前事项已由学生事务中心人工接单。</div><div class="handoff-timeline effective-info"><div><time>11:42</time><p><b>学生事务中心已接单</b><span>处理人：王老师 · 服务台 2 号</span></p></div><div><time>11:46</time><p><b>已查看当前会话公开访问摘要</b><span>历史归档、旧论坛与人员状态交叉检索记录</span></p></div><div><time>11:52</time><p><b>学生联系方式呼叫未接通</b><span>沿用在籍学生事务联系方式</span></p></div><div><time>11:56</time><p><b>监护联系方式通知已发送</b><span>当前页面不提供通知正文或回执原件</span></p></div><div><time>12:03</time><p><b>已加入 18:40 接驳名单</b><span>校车 03 · 青岚青少年成长实践中心 · 1人</span></p></div></div><div class="audit-grid effective-info"><div><span>历史归档访问</span><b>${a.history}</b></div><div><span>旧帖访问</span><b>${a.forum}</b></div><div><span>站内检索词</span><b>${a.searches}</b></div><div><span>人员交叉查询</span><b>${a.people}</b></div></div><div class="attention-index effective-info"><span>当前访问质量指数</span><b>${a.score}</b></div><button class="btn review-primary" type="button" id="review-ack">确认已知晓核验安排</button></section>
  <section class="panel"><h2 class="section-title">近年同类事项 <small>公开状态交叉摘要</small></h2><div class="table-wrap mobile-cards effective-info"><table class="data-table"><thead><tr><th>年份</th><th>公开账户</th><th>最后公开查询</th><th>后续事项</th><th>之后公开状态</th></tr></thead><tbody><tr><td data-label="年份">2017</td><td data-label="公开账户">陈*</td><td data-label="最后公开查询">旧值班表版本</td><td data-label="后续事项">学生事务补充核验</td><td data-label="之后公开状态">校际转出 / 去向未公开</td></tr><tr><td data-label="年份">2019</td><td data-label="公开账户">周*</td><td data-label="最后公开查询">旧门禁归档</td><td data-label="后续事项">18:40 接驳 / 青岚</td><td data-label="之后公开状态">个人原因休学</td></tr><tr><td data-label="年份">2022</td><td data-label="公开账户">林*</td><td data-label="最后公开查询">返校旧索引</td><td data-label="后续事项">09:20 接驳 / 青岚</td><td data-label="之后公开状态">家庭原因暂缓返校</td></tr><tr class="focus-row"><td data-label="年份">2026</td><td data-label="公开账户">当前账户</td><td data-label="最后公开查询">合作机构与历史处置缓存</td><td data-label="后续事项"><b>18:40 接驳 / 青岚</b></td><td data-label="之后公开状态">—</td></tr></tbody></table></div><p class="small muted">同类事项的公开状态来自不同年度系统；本页不声称三人的实际去向完全相同。</p></section>
  <section class="panel"><h2 class="section-title">学籍异动预处理 <small>尚未生效</small></h2><div class="future-record-grid effective-info"><div><span>申请来源</span><b>本人</b></div><div><span>公开事由</span><b>家庭长期迁居</b></div><div><span>监护确认</span><b>已完成</b></div><div><span>拟生效日期</span><b>明日</b></div></div><p class="small muted">本页仅显示预处理摘要。当前会话未提供对应申请单、监护确认原件或撤销入口。</p></section>
  <section class="panel"><h2 class="section-title">校园广场草稿同步</h2><div class="draft-ghost effective-info"><div class="tiny muted">作者：当前学生账户 · 计划发布时间：明日 07:20</div><p><b>最近家里有点事</b></p><p>这学期可能不过来了。之前问过的那些旧资料不用管了，我应该看错了。</p></div><p class="small muted">当前账户没有已提交的公开主题。该草稿来自跨端同步缓存。</p></section>
  <section class="panel"><h2 class="section-title">处理当前事项</h2><p>当前页面没有提供取消 18:40 接驳的单独入口。你仍可以决定是否让已经整理出的材料留在学校公开系统中。</p><div class="choice-grid"><div class="choice"><h3>结束当前查询</h3><p>不再提交材料，也不公开反馈历史异常。</p><div class="cost">公开影响：不新增任何可检索记录。</div><button class="btn" data-final="stop">结束查询</button></div><div class="choice"><h3>提交公开反馈</h3><p>把发现的异常以校园广场问题反馈形式提交。</p><div class="cost">公开影响：主题可能进入缓存与内容清理流程。</div><button class="btn" data-final="public">提交公开反馈</button></div><div class="choice"><h3>提交完整归档材料</h3><p>把访问记录、旧帖、合作机构与公开状态交叉材料写入校史附件队列。</p><div class="cost">公开影响：附件可能保留到下一学年索引预同步。</div><button class="btn primary" data-final="archive">提交归档材料</button></div></div></section></div><aside class="sidebar"><div class="card"><h3 class="section-title">事项信息</h3><div class="small effective-info">集合：综合服务楼西门</div><div class="small effective-info">班次：18:40 / 校车 03</div><div class="small effective-info">目的地：青岚青少年成长实践中心</div></div><div class="card"><h3 class="section-title">已核对公开资料</h3><a href="history-detail.html?id=hist_attention_cache">访问质量抽样摘要</a><br><a href="history-detail.html?id=hist_deleted_reply_cache_2019">2019 删除回复缓存</a><br><a href="history-detail.html?id=hist_center_incident_2019">2019 夜间处置残页</a><br><a href="history-detail.html?id=hist_lin_transfer_2022">2022 接驳调度摘要</a></div><div class="card"><h3 class="section-title">合作机构</h3><a href="center.html">青岚青少年成长实践中心</a></div></aside></div>`;
  const ack=document.getElementById('review-ack');ack?.addEventListener('click',()=>{ack.textContent='已知晓';ack.disabled=true});maybeReviewButtonFlicker(ack);
  document.querySelectorAll('[data-final]').forEach(b=>b.addEventListener('click',()=>{const kind=b.dataset.final;if(!reviewReady())return;setFinalChoice(kind);playCue('notice');location.href=`review.html?end=${encodeURIComponent(kind)}`}));
  refreshShared();
}
