import {pageRoot,crumb,fetchJSON,showLoadError,refreshShared,safeText} from './app.js';
import {postRows} from './render.js';
import {flag} from './state.js';
(async()=>{try{
 const data=await fetchJSON('data/posts.json');flag('viewedSquare');const p=new URLSearchParams(location.search);const y=p.get('year')||'2026';const month=p.get('month')||'08';const sort=p.get('sort')||'time';const q=(p.get('q')||'').trim();
 let items=data.filter(x=>x.date.startsWith(`${y}-${month}`));if(q)items=items.filter(x=>(x.title+x.author+x.category+x.summary).includes(q));
 if(sort==='hot')items=[...items].sort((a,b)=>(b.replies||0)-(a.replies||0)||b.date.localeCompare(a.date));else if(sort==='archive')items=[...items].sort((a,b)=>a.date.localeCompare(b.date));else items=[...items].sort((a,b)=>b.date.localeCompare(a.date));
 const tab=(id,label)=>`<a class="${sort===id?'active':''}" href="square.html?year=${encodeURIComponent(y)}&month=${encodeURIComponent(month)}&sort=${id}${q?`&q=${encodeURIComponent(q)}`:''}">${label}</a>`;
 pageRoot().innerHTML=`${crumb([{label:'校园广场'}])}<section class="forum-shell"><div class="forum-head"><b>栖岚校园广场 · 公开归档</b><span class="tiny">归档月份 ${safeText(y)} / ${safeText(month)}</span></div><div style="padding:12px;background:#fff;border-bottom:1px solid #ccc"><form class="searchbar" method="get"><select class="form-control" name="year" style="max-width:150px"><option value="2026" ${y==='2026'?'selected':''}>2026</option><option value="2022" ${y==='2022'?'selected':''}>2022</option><option value="2021" ${y==='2021'?'selected':''}>2021</option></select><select class="form-control" name="month" style="max-width:130px"><option value="08" ${month==='08'?'selected':''}>8 月</option><option value="09" ${month==='09'?'selected':''}>9 月</option></select><input type="hidden" name="sort" value="${safeText(sort)}"><input class="form-control" name="q" value="${safeText(q)}" placeholder="搜索公开话题、作者或关键词"><button class="btn" type="submit">搜索</button></form></div><div class="forum-tabs">${tab('time','按时间')}${tab('hot','热门')}${tab('archive','公开归档')}</div><div class="forum-post-list">${postRows(items)}</div></section><div class="notice-box small">校园广场归档仅包含当年公开帖子与公开回复，不包含私信、删除内容或私人联系方式。</div>`;refreshShared()
}catch(e){showLoadError(e)}})();
